imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @DTLTravelBundle/Resources/config/autoroute.yml }

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [CmfSimpleCmsBundle, CmfCreateBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #lessphp:
            #file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            #apply_to: "\.less$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# for jackalope-doctrine-dbal
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        path:     %database_path%
        charset:  UTF8

# cmf configuration
doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_pass%
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%
        locales:
            en:
                - de
            de:
                - en
        mappings:
            SonataMediaBundle:
                prefix: Sonata\MediaBundle\PHPCR
            SandboxMediaBundle:
                prefix: Sandbox\MediaBundle\Document

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        routing_repositoryroot: /cms/routes
        generic_controller: cmf_content.controller:indexAction
        controllers_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: cmf_content.controller:indexAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Blog: cmf_blog.blog_controller:listAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Post: cmf_blog.blog_controller:viewPostAction
            DTL\TravelBundle\Document\ChronoDate: DTLTravelBundle:Chronology:date

        controllers_by_type:
            travel_blog_chronology: DTLTravelBundle:Chronology:index
            travel_blog_map: DTLTravelBundle:Map:index

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: DTLTravelBundle:StaticContent:layout.html.twig


knp_menu:
    twig: 
        template: DTLTravelBundle::knp_menu.html.twig

cmf_menu:
    use_sonata_admin: true
    menu_basepath: /cms/menu

sonata_admin:
    dashboard:
        blocks:
            - 
                position: left
                type: sonata.admin.block.admin_list

sonata_media:
    default_context: default
    db_driver: doctrine_phpcr

    contexts:
        default:  # the default context is mandatory
            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
                - sonata.media.provider.image
#                - sonata.media.provider.file

            formats:
                tiny: { width: 50 , quality: 70}
                small: { width: 100 , quality: 70}
                big:   { width: 1024 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
    class:
        media:              Sandbox\MediaBundle\Document\Media
        gallery:            Sandbox\MediaBundle\Document\Gallery
        gallery_has_media:  Sandbox\MediaBundle\Document\GalleryHasMedia

cmf_blog:
    blog_basepath: /cms/content
    class:
        post: DTL\TravelBundle\Document\VoyagePost
        post_admin: DTL\TravelBundle\Admin\PostAdmin

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

dtl_time_distance:

sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all

cmf_block:
    document_manager_name:  default
